[tool.poetry]
name = "csp"
version = "0.1.27" 
description = "DLM internal SQL connector utilities"
authors = ["DLM Consultancy <dev@dlm.co.id>"]
packages = [{ include = "csp" }]
readme = "README.md"
include = ["csp/.env.example"]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
pandas = "^2.2"
sqlalchemy = "^2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
csp-init-env = "csp:copy_env_example"
